<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RaviS5-MSD" ignored="0" name="Default test" tests="3" failures="0" timestamp="06 Dec 2018 06:37:30 GMT" time="0.084" errors="0">
  <testcase name="@BeforeMethod Setup" time="0.015" classname="com.qa.TestCases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.Base.Base_Class.Intilization(Base_Class.java:54)
at com.qa.TestCases.LoginTest.Setup(LoginTest.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:520)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeMethod Setup -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.qa.TestCases.LoginTest">
    <skipped/>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@BeforeMethod Setup" time="0.0" classname="com.qa.TestCases.LoginTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod Setup -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.qa.TestCases.LoginTest">
    <skipped/>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="Logintest" time="0.0" classname="com.qa.TestCases.LoginTest">
    <skipped/>
  </testcase> <!-- Logintest -->
  <testcase name="ValidateCRMLogo" time="0.0" classname="com.qa.TestCases.LoginTest">
    <skipped/>
  </testcase> <!-- ValidateCRMLogo -->
  <testcase name="ValidateTitlePage" time="0.0" classname="com.qa.TestCases.LoginTest">
    <skipped/>
  </testcase> <!-- ValidateTitlePage -->
</testsuite> <!-- Default test -->
